### ISSUE TITLE
Error reading in specifications for sound from xml

### ISSUE THREAD

**Issue by purvigoel** [wphicks/Writing3D#21]
I get the following traceback when attempting to run Ode using cwapp.py

Traceback (most recent call last):
  File "cwapp.py", line 50, in <module>
    my_project = project.W3DProject.fromXML_file(args.project_file)
  File "/Users/purvigoel/Library/Python/3.4/lib/python/site-packages/pyw3d/project.py", line 374, in fromXML_file
    return project_class.fromXML(ET.parse(filename).getroot())
  File "/Users/purvigoel/Library/Python/3.4/lib/python/site-packages/pyw3d/project.py", line 307, in fromXML
    new_project["sounds"].append(W3DSound.fromXML(child))
  File "/Users/purvigoel/Library/Python/3.4/lib/python/site-packages/pyw3d/sounds.py", line 160, in fromXML
    for key, value in xml_map:
ValueError: too many values to unpack (expected 2)

**Comment by wphicks** [comment]
Resolved by c37e0ed
