### ISSUE TITLE
key "linV" doesn't exist

### ISSUE THREAD

**Issue by purvigoel** [wphicks/Writing3D#39]
When running sample_random.xml, I get the following traceback:

Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in activate
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in <listcomp>
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in activate
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in <listcomp>
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in activate
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in <listcomp>
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in activate
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in <listcomp>
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in activate
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in <listcomp>
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'

However, a more minimal sample that contains a restarting timeline and random movements does not throw these errors and actually functions correctly.

**Comment by purvigoel** [comment]
Here's the debug statements that print in and around the traceback. It looks like we see tracebacks whenever a movement in timeline 1 ends.

2016-08-22 12:27:16,982    DEBUG W3D Ending movement in timeline_1
2016-08-22 12:27:16,999    DEBUG W3D activate called on timeline_1 with status Continue
2016-08-22 12:27:17,000    DEBUG W3D Action Index 2 at time 1.0876037903126416 on timeline_1
2016-08-22 12:27:17,000    DEBUG W3D Ending movement in timeline_1
2016-08-22 12:27:17,015    DEBUG W3D activate called on timeline_1 with status Continue
2016-08-22 12:27:17,015    DEBUG W3D Action Index 2 at time 1.102446680312596 on timeline_1
2016-08-22 12:27:17,015    DEBUG W3D Ending movement in timeline_1
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in activate
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in <listcomp>
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
2016-08-22 12:27:17,032    DEBUG W3D activate called on timeline_1 with status Continue
2016-08-22 12:27:17,032    DEBUG W3D Action Index 2 at time 1.1194446203126063 on timeline_1
2016-08-22 12:27:17,032    DEBUG W3D Ending movement in timeline_1
2016-08-22 12:27:17,049    DEBUG W3D activate called on timeline_1 with status Continue
2016-08-22 12:27:17,049    DEBUG W3D Action Index 2 at time 1.1372218133126353 on timeline_1
2016-08-22 12:27:17,050    DEBUG W3D Ending movement in timeline_1
Python script error - object 'timeline_1', controller 'activate':
Traceback (most recent call last):
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in activate
  File "/Users/purvigoel/Downloads/CaveWriting/samples/run.blend/timeline_1.py", line 103, in <listcomp>
KeyError: 'value = gameOb[key]: KX_GameObject, key "linV" does not exist'
2016-08-22 12:27:17,065    DEBUG W3D activate called on timeline_1 with status Continue
2016-08-22 12:27:17,065    DEBUG W3D Action Index 2 at time 1.152467788312606 on timeline_1
2016-08-22 12:27:17,065    DEBUG W3D Ending movement in timeline_1

**Comment by purvigoel** [comment]
I do think it's still a timing thing, though, because changing the timeline reset time in the follow code (around line 90 of sample_random.xml) from 1.5 to anything less than 1.0 seconds makes the program work without a traceback.

`<TimedActions seconds-time="1.0">
                            <TimerChange name="1">
                                   <start/>
                            </TimerChange>
                     </TimedActions>`

**Comment by purvigoel** [comment]
I'm still not sure what's causing the problem, but was able to construct a band-aid solution by saying that if linV didn't exist, to make it [0,0,0] in the continue_string: 

`if "position" in self.placement:`
`script_text.extend([`
`"if 'linV' not in blender_object:",`
`"   blender_object['linV'] = [0.0,0.0,0.0]",`
`"blender_object.position = [",`
 `"    blender_object.position[i] + blender_object['linV'][i]",`
`"    for i in range(len(blender_object.position))]",`
 `"W3D_LOG.debug('linV is {}'.format(blender_object['linV']))"]`
`)`

That stops it from throwing errors. But I'm not sure if it's just a short cut solution rather than a real solution.

**Comment by purvigoel** [comment]
I've been experimenting with times and I think I gained some insight on where the problem is. The project will consistently throw errors during the second timeline action--and only the second timeline action. The first timeline action in my version of sample_random starts at 0.5 seconds, with a duration of 0.9 seconds. The second timeline action starts 1.4 seconds in, with a duration of 0.5 seconds. The timeline restarts after 1.9 seconds total.

The errors will be thrown from 1.4 seconds in  to 1.9 seconds in. They'll stop when the first timeline action is replaying, and then come up again, consistently, during the second timeline action.

The pattern still exists when I adjust the times.

**Comment by wphicks** [comment]
Ah, excellent. That makes some sense to me, but I'm going to have to probe deeper on it. Thanks for the update!

**Comment by wphicks** [comment]
I think this is no longer an issue in the latest develop version. I'll re-open if it turns out I'm wrong.
