### ISSUE TITLE
projects crash if glyphs are missing from a font

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#91]
* we should report this as a warning and prevent the crash
* we will need a list of glyphs for the default "BFont" file, which I plan to encourage students to use in the first instance
* to reproduce: 1) put a 'pipe' or a 'bullet' character (option-8 on a Mac) into the text field of a text object, 2) leave the font field blank, 3) attempt to preview the project

**Comment by shadoof** [comment]
INVOCATION >> /Users/kongqi/W3D/blender/blender.app/Contents/MacOS/blender --background --python /Users/kongqi/W3D/Writing3D/scripts/Mac/../../samples/cwapp.py -- desktop /Users/kongqi/GDrive/BrownGDrive2013/Courses/Writing3D/Writing3D_XML_Samples/sample_00_random.xml
found bundled python: /Users/kongqi/W3D/blender/blender.app/Contents/MacOS/../Resources/2.76/python
W3D Configuration loaded from /Users/kongqi/.w3d.json
Configuration information:  {'Export script path': '/Users/kongqi/W3D/Writing3D/pyw3d/w3d_export_tools.py', 'Blender executable': '/Users/kongqi/W3D/blender/blender.app/Contents/MacOS/blender', 'Blender player executable': '/Users/kongqi/W3D/blender/blenderplayer.app/Contents/MacOS/blenderplayer'}
Traceback (most recent call last):
  File "/Users/kongqi/W3D/Writing3D/scripts/Mac/../../samples/cwapp.py", line 67, in <module>
    fullscreen=(args.config == "desktopfull")
  File "/Users/kongqi/W3D/Writing3D/pyw3d/w3d_export_tools.py", line 51, in export_to_blender
    input_project.blend()
  File "/Users/kongqi/W3D/Writing3D/pyw3d/project.py", line 553, in blend
    self._blend()
  File "/Users/kongqi/W3D/Writing3D/pyw3d/project.py", line 588, in _blend
    object_.blend()
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 1082, in blend
    blender_object = self["content"].blend()
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 610, in blend
    apply_euler_rotation(final_object, math.pi / 2, 0, 0)
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 69, in apply_euler_rotation
    blender_object.data.transform(
AttributeError: 'NoneType' object has no attribute 'transform'

**Comment by wphicks** [comment]
Possibly related to #78.

**Comment by wphicks** [comment]
Note to self: Probably best to just drop an empty into the scene when this happens. No other default seems sensible.
