### ISSUE TITLE
Check which samples from old cwapp are failing

### ISSUE THREAD

**Issue by wphicks** [wphicks/Writing3D#92]
Some old cwapp samples are not running properly on the new system

**Comment by shadoof** [comment]
INVOCATION >> /Users/kongqi/W3D/blender/blender.app/Contents/MacOS/blender --background --python /Users/kongqi/W3D/Writing3D/scripts/Mac/../../samples/cwapp.py -- desktop /Users/kongqi/CaveWriting/samples/sample.xml
found bundled python: /Users/kongqi/W3D/blender/blender.app/Contents/MacOS/../Resources/2.76/python
Traceback (most recent call last):
  File "/Users/kongqi/W3D/Writing3D/scripts/Mac/../../samples/cwapp.py", line 61, in <module>
    my_project = project.W3DProject.fromXML_file(args.project_file)
  File "/Users/kongqi/W3D/Writing3D/pyw3d/project.py", line 426, in fromXML_file
    ET.parse(filename).getroot(), call_directory)
  File "/Users/kongqi/W3D/Writing3D/pyw3d/project.py", line 334, in fromXML
    new_project["objects"].append(W3DObject.fromXML(child))
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 1045, in fromXML
    new_object["content"] = W3DContent.fromXML(node)
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 366, in fromXML
    return W3DText.fromXML(content_root)
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 534, in fromXML
    new_text["font"] = text_root.attrib["font"]
  File "/Users/kongqi/W3D/Writing3D/pyw3d/features.py", line 84, in __setitem__
    value, key, self.argument_validators[key].help_string))
pyw3d.errors.InvalidArgument: Courier.ttf is not a valid value for option font
Additional Info: Could not find file /Users/kongqi/CaveWriting/samples/Courier.ttf
W3D Configuration loaded from /Users/kongqi/.w3d.json
Configuration information:  {'Blender player executable': '/Users/kongqi/W3D/blender/blenderplayer.app/Contents/MacOS/blenderplayer', 'Blender executable': '/Users/kongqi/W3D/blender/blender.app/Contents/MacOS/blender', 'Export script path': '/Users/kongqi/W3D/Writing3D/pyw3d/w3d_export_tools.py'}

Blender quit

**Comment by shadoof** [comment]
Closing this because we will be working thought the w3d_samples repo and generating tickets on a per-issue basis (as far as possible).

**Comment by wphicks** [comment]
Great, thanks! I think this is a good workflow for these.
