### ISSUE TITLE
Object (as obj file) does not work in sample_04_model.xml and causes crash

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#94]
from the log file:
INVOCATION >> /Users/kongqi/W3D/blender/blender.app/Contents/MacOS/blender --background --python /Users/kongqi/W3D/Writing3D/scripts/Mac/../../samples/cwapp.py -- desktop /Users/kongqi/GDrive/BrownGDrive2013/Courses/Writing3D/Writing3D_XML_Samples/sample_04_model.xml
found bundled python: /Users/kongqi/W3D/blender/blender.app/Contents/MacOS/../Resources/2.76/python
Error: Unable to pack file, source path 'ArmyOfDarkness.jpg' not found
Info: Packed 15 files
Traceback (most recent call last):
  File "/Users/kongqi/W3D/Writing3D/scripts/Mac/../../samples/cwapp.py", line 67, in <module>
    fullscreen=(args.config == "desktopfull")
  File "/Users/kongqi/W3D/Writing3D/pyw3d/w3d_export_tools.py", line 51, in export_to_blender
    input_project.blend()
  File "/Users/kongqi/W3D/Writing3D/pyw3d/project.py", line 553, in blend
    self._blend()
  File "/Users/kongqi/W3D/Writing3D/pyw3d/project.py", line 619, in _blend
    bpy.ops.file.pack_all()
  File "/Users/kongqi/W3D/blender/blender.app/Contents/MacOS/../Resources/2.76/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Unable to pack file, source path 'ArmyOfDarkness.jpg' not found

W3D Configuration loaded from /Users/kongqi/.w3d.json
Configuration information:  {'Blender executable': '/Users/kongqi/W3D/blender/blender.app/Contents/MacOS/blender', 'Blender player executable': '/Users/kongqi/W3D/blender/blenderplayer.app/Contents/MacOS/blenderplayer', 'Export script path': '/Users/kongqi/W3D/Writing3D/pyw3d/w3d_export_tools.py'}
Progress:   0.00%
(  0.0001 sec |   0.0001 sec) Importing OBJ './models/bathroom2.obj'...
Progress:   0.00%
  (  0.0006 sec |   0.0005 sec) Parsing OBJ file...
Progress:   0.00%
    (  0.3811 sec |   0.3804 sec) Done, loading materials and images...
Progress:  33.33%
    (  0.3946 sec |   0.3940 sec) Done, building geometries (verts:5989 faces:11642 materials: 21 smoothgroups:16) ...
Progress:  66.67%
    (  1.0301 sec |   1.0294 sec) Done.
Progress:  66.67%
Progress: 100.00%
  (  1.0302 sec |   1.0301 sec) Finished importing: './models/bathroom2.obj'
Progress: 100.00%
Progress: 100.00%

Error: Unable to pack file, source path 'ArmyOfDarkness.jpg' not found
Info: Packed 15 files

Blender quit

**Comment by wphicks** [comment]
Interpreting the log here, the problem is that the image used to texture the model is unavailable. It looks like the obj itself imported cleanly. I'll check to see where it's looking for assets as it's doing texturing stuff. I know I've gotten this sample to work in the past, so I'm not *too* concerned.
