### ISSUE TITLE
stereo images not working in sample_07_stereoimage.xml

### ISSUE THREAD

**Issue by shadoof** [wphicks/Writing3D#95]
from the log file:
INVOCATION >> /Users/kongqi/W3D/blender/blender.app/Contents/MacOS/blender --background --python /Users/kongqi/W3D/Writing3D/scripts/Mac/../../samples/cwapp.py -- desktop /Users/kongqi/GDrive/BrownGDrive2013/Courses/Writing3D/Writing3D_XML_Samples/sample_07_stereoimage.xml
found bundled python: /Users/kongqi/W3D/blender/blender.app/Contents/MacOS/../Resources/2.76/python
Traceback (most recent call last):
  File "/Users/kongqi/W3D/Writing3D/scripts/Mac/../../samples/cwapp.py", line 67, in <module>
    fullscreen=(args.config == "desktopfull")
  File "/Users/kongqi/W3D/Writing3D/pyw3d/w3d_export_tools.py", line 51, in export_to_blender
    input_project.blend()
  File "/Users/kongqi/W3D/Writing3D/pyw3d/project.py", line 553, in blend
    self._blend()
  File "/Users/kongqi/W3D/Writing3D/pyw3d/project.py", line 588, in _blend
    object_.blend()
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 1082, in blend
    blender_object = self["content"].blend()
  File "/Users/kongqi/W3D/Writing3D/pyw3d/objects.py", line 723, in blend
    raise NotImplementedError  # TODO
NotImplementedError
W3D Configuration loaded from /Users/kongqi/.w3d.json
Configuration information:  {'Blender player executable': '/Users/kongqi/W3D/blender/blenderplayer.app/Contents/MacOS/blenderplayer', 'Export script path': '/Users/kongqi/W3D/Writing3D/pyw3d/w3d_export_tools.py', 'Blender executable': '/Users/kongqi/W3D/blender/blender.app/Contents/MacOS/blender'}

Blender quit

**Comment by wphicks** [comment]
Merging this with #36, but it's good to have it documented in terms of which legacy samples are affected by this.
